hiveservice:
  replicaCount: 3
  image:
    repository: art-hq.intranet.qualys.com:5001/k8s.gcr.io/hiveservice
    tag: 0.1.0
    pullPolicy: IfNotPresent
  ingress:
    enabled: false
  service:
    type: ClusterIP
    portThrift: 9083
  resources:
    requests:
      cpu: 100m
  nodeSelector: {}
  tolerations: []
  affinity: {}
