hiveservice:
  replicaCount: 1
  image:
    repository: art-hq.intranet.qualys.com:5001/datalake/hiveservice
    tag: 0.1.12
    pullPolicy: IfNotPresent
  ingress:
    enabled: false
  service:
    type: ClusterIP
    portThrift: 9083
  resources:
    requests:
      cpu: 100m
  nodeSelector: {}
  tolerations: []
  affinity: {}

spark:
  replicaCount: 1
  image:
    spark:
      repository: art-hq.intranet.qualys.com:5001/datalake/spark
      tag: 0.2.10
      pullPolicy: IfNotPresent
    proxy:
      repository: art-hq.intranet.qualys.com:5001/k8s.gcr.io/spark-ui-proxy
      tag: "1.0"
      pullPolicy: IfNotPresent
  ingress:
    enabled: false
  service:
    spark:
      type: None
      portUI: 8080
      portRPC: 7077
    proxy:
      type: NodePort
      port: 80
      nodePortUI: 30006
  resources:
    requests:
      cpu: 100m
  nodeSelector: {}
  tolerations: []
  affinity: {}
