apiVersion: apps/v1
kind: Deployment
metadata:
  name: druid-broker-deployment
  labels:
    app: druid-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: druid-broker
  template:
    metadata:
      labels:
        app: druid-broker
    spec:
      hostname: druid-broker
      containers:
      - name: druid-broker
        command: ["/opt/druid-0.12.3/bin/broker.sh", "start"]
        image: art-hq.intranet.qualys.com:5001/datalake/druid-base:0.2.0
        ports:
        - containerPort: 8082
        resources:
          requests:
            memory: 8Gi
