apiVersion: apps/v1
kind: Deployment
metadata:
  name: druid-coordinator-deployment
  labels:
    app: druid-coordinator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: druid-coordinator
  template:
    metadata:
      labels:
        app: druid-coordinator
    spec:
      hostname: druid-coordinator
      containers:
      - name: druid-coordinator
        command: ["/opt/druid-0.12.3/bin/coordinator.sh", "start"]
        image: art-hq.intranet.qualys.com:5001/datalake/druid-base:0.2.0
        ports:
        - containerPort: 8081
