apiVersion: apps/v1
kind: Deployment
metadata:
  name: druid-historical-deployment
  labels:
    app: druid-historical
spec:
  replicas: 1
  selector:
    matchLabels:
      app: druid-historical
  template:
    metadata:
      labels:
        app: druid-historical
    spec:
      hostname: druid-historical
      containers:
      - name: druid-historical
        command: ["/opt/druid-0.12.3/bin/historical.sh", "start"]
        image: art-hq.intranet.qualys.com:5001/datalake/druid-base:0.2.8
        ports:
        - containerPort: 8083
        resources:
          requests:
            memory: 8Gi
