apiVersion: apps/v1
kind: Deployment
metadata:
  name: druid-middlemanager-deployment
  labels:
    app: druid-middlemanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: druid-middlemanager
  template:
    metadata:
      labels:
        app: druid-middlemanager
    spec:
      hostname: druid-middlemanager
      containers:
      - name: druid-middlemanager
        command: ["/opt/druid-0.12.3/bin/middleManager.sh", "start"]
        image: art-hq.intranet.qualys.com:5001/datalake/druid-base:0.2.0
        ports:
        - containerPort: 8091
        resources:
          requests:
            memory: 8Gi
