apiVersion: v1
kind: Service
metadata:
  name: druid-overlord
  labels:
    name: druid-overlord
spec:
  type: NodePort
  ports:
  - port: 8090
    nodePort: 30761
  selector:
    app: druid-overlord
