apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.namespace | quote }}
  name: {{ template "datalake.alluxio.fullname" . }}
  labels:
    app: {{ template "datalake.alluxio.name" . }}
    chart: {{ template "datalake.subchart" . }}
    release: {{ .Release.Name }}
data:
  ALLUXIO_CONFIG: |-
    alluxio.security.authentication.type=SIMPLE
    alluxio.security.login.username=root
    alluxio.master.hostname=alluxio-master
    alluxio.underfs.address=/gluster
    alluxio.worker.memory.size=2GB
    alluxio.user.file.delete.unchecked=true
