kind: PersistentVolume
apiVersion: v1
metadata:
  namespace: {{ .Values.namespace | quote }}
  name: {{ template "datalake.alluxio.fullname" . }}
  labels:
    app: {{ template "datalake.alluxio.name" . }}
    chart: {{ template "datalake.subchart" . }}
    release: {{ .Release.Name }}
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp/data"
