apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Values.namespace | quote }}
  name: {{ template "datalake.alluxio.fullname" . }}
  labels:
    app: {{ template "datalake.alluxio.name" . }}
    chart: {{ template "datalake.subchart" . }}
    release: {{ .Release.Name }}
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{ .Values.namespace | quote }}
  name: "{{ .Release.Name }}-{{ template "datalake.alluxio.alluxio-master" . }}"
  labels:
    app: {{ template "datalake.alluxio.name" . }}
    chart: {{ template "datalake.subchart" . }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ template "datalake.alluxio.alluxio-master" . }}
  serviceName: "alluxio-master"
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "datalake.alluxio.alluxio-master" . }}
    spec:
      hostNetwork: true
      hostPID: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          pullPolicy: {{ .Values.image.pullPolicy | quote }}
          resources:
            requests:
              cpu: "0.5"
              memory: "512M"
            limits:
              cpu: "1"
              memory: "1024M"
          command: ["/entrypoint.sh"]
          args: ["master"]
          env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              configMapKeyRef:
                name: {{ template "datalake.alluxio.fullname" . }}
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              configMapKeyRef:
                name: {{ template "datalake.alluxio.fullname" . }}
                key: AWS_SECRET_ACCESS_KEY
          envFrom:
          - configMapRef:
              name: {{ template "datalake.alluxio.fullname" . }}
          ports:
          - containerPort: 19998
            name: rpc
          - containerPort: 19999
            name: web
          volumeMounts:
            - name: alluxio-journal
              mountPath: /journal
            - name: alluxio-domain
              mountPath: /opt/domain
            - name: alluxio-gluster
              mountPath: /gluster
      restartPolicy: Always
      volumes:
        - name: alluxio-journal
          persistentVolumeClaim:
            claimName: {{ template "datalake.alluxio.fullname" . }}
        - name: alluxio-domain
          hostPath:
            path: {{ .Values.hostShortCircuit | quote }}
            type: Directory
        - name: alluxio-gluster
          hostPath:
            path: {{ .Values.hostUnderfs | quote }}
            type: Directory
