apiVersion: v1
kind: Service
metadata:
  name: alluxio-master
  namespace: {{ .Values.namespace | quote }}
  labels:
    app: {{ template "datalake.alluxio.name" . }}
    chart: {{ template "datalake.subchart" . }}
    release: {{ .Release.Name }}
spec:
  ports:
  - port: 19998
    name: rpc
  - port: 19999
    name: web
  clusterIP: None
  selector:
    app: alluxio-master