apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: {{ .Values.namespace | quote }}
  name: {{ template "datalake.alluxio.fullname" . }}
  labels:
    app: {{ template "datalake.alluxio.name" . }}
    chart: {{ template "datalake.subchart" . }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      name: {{ template "datalake.alluxio.alluxio-worker" . }}
  template:
    metadata:
      labels:
        name: {{ template "datalake.alluxio.alluxio-worker" . }}
    spec:
      hostNetwork: true
      hostPID: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: {{ template "datalake.alluxio.alluxio-worker" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          pullPolicy: {{ .Values.image.pullPolicy | quote }}
          resources:
            requests:
              cpu: "0.5"
              memory: "2G"
            limits:
              cpu: "1"
              memory: "2G"
          command: ["/entrypoint.sh"]
          args: ["worker"]
          env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              configMapKeyRef:
                name: {{ template "datalake.alluxio.fullname" . }}
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              configMapKeyRef:
                name: {{ template "datalake.alluxio.fullname" . }}
                key: AWS_SECRET_ACCESS_KEY
          - name: ALLUXIO_WORKER_HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          envFrom:
          - configMapRef:
              name: {{ template "datalake.alluxio.fullname" . }}
          ports:
          - containerPort: 29998
            name: rpc
          - containerPort: 29999
            name: data
          - containerPort: 29996
            name: web
          securityContext:
            privileged: true
          volumeMounts:
            - name: alluxio-ramdisk
              mountPath: /dev/shm
            - name: alluxio-domain
              mountPath: /opt/domain
            - name: alluxio-gluster
              mountPath: /gluster
      restartPolicy: Always
      volumes:
        - name: alluxio-ramdisk
          emptyDir:
            medium: "Memory"
            sizeLimit: "1G"
        - name: alluxio-domain
          hostPath:
            path: {{ .Values.hostShortCircuit | quote }}
            type: Directory
        - name: alluxio-gluster
          hostPath:
            path: {{ .Values.hostUnderfs | quote }}
            type: Directory
