apiVersion: v1
kind: Service
metadata:
  name: {{ template "datalake.zeppelin.hostname" . }}
  namespace: {{ .Values.namespace | quote }}
  labels:
    app: {{ template "datalake.zeppelin.name" . }}
    chart: {{ template "datalake.subchart" . }}
    release: {{ .Release.Name }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "datalake.zeppelin.name" . }}
    release: {{ .Release.Name }}
