apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    app: {{ template "datalake.postgresql.name" . }}
    chart: {{ template "datalake.subchart" . }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: postgresql
    port: {{ .Values.service.port }}
    targetPort: postgresql
  {{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePort))) }}
    nodePort: {{ .Values.service.nodePort }}
  {{- end }}
{{- if .Values.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.service.externalIPs | indent 4 }}
{{- end }}
  selector:
    app: {{ template "datalake.postgresql.name" . }}
    release: {{ .Release.Name }}
