apiVersion: v1
kind: Secret
metadata:
  name: {{ template "datalake.postgresql.fullname" . }}
  labels:
    app: {{ template "datalake.postgresql.name" . }}
    chart: {{ template "datalake.subchart" . }}
    release: {{ .Release.Name }}
type: Opaque
data:
  {{ if .Values.postgresPassword }}
  postgres-password:  {{ .Values.postgresPassword | b64enc | quote }}
  {{ else }}
  postgres-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
