apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "datalake.spark-hadoop-master.fullname" . }}
  labels:
    app: {{ template "datalake.spark-hadoop-master.name" . }}
    chart: {{ template "datalake.subchart" . }}
    release: {{ .Release.Name }}
data:
  spark-defaults.conf: |
    spark.master spark://spark--hadoop-master:7077
    spark.app.id QualysSpark
    spark.hadoop.datanucleus.autoCreateSchema false
    spark.executor.memory 8g
    spark.executor.memoryOverhead   384m
    spark.driver.memory 4g
    spark.driver.memoryOverhead  384m
    spark.scheduler.minRegisteredResourcesRatio 0.8
    spark.sql.hive.metastore.version 3.1.0
    spark.sql.hive.metastore.schema.verification false

  hive-site.xml: |
    <configuration>
      <property>
        <name>javax.jdo.option.ConnectionURL</name>
        <value>jdbc:postgresql://postgresql:5432/metastore</value>
      </property>
      <property>
        <name>javax.jdo.option.ConnectionDriverName</name>
        <value>org.postgresql.Driver</value>
      </property>
      <property>
        <name>javax.jdo.option.ConnectionUserName</name>
        <value>hive</value>
      </property>
      <property>
        <name>javax.jdo.option.ConnectionPassword</name>
        <value>hive</value>
      </property>
      <property>
        <name>hive.execution.engine</name>
        <value>spark</value>
      </property>
      <property>
        <name>fs.alluxio.impl</name>
        <value>alluxio.hadoop.FileSystem</value>
        <description>The Alluxio FileSystem (Hadoop 1.x and 2.x)</description>
      </property>
      <property>
        <name>fs.AbstractFileSystem.alluxio.impl</name>
        <value>alluxio.hadoop.AlluxioFileSystem</value>
        <description>The Alluxio AbstractFileSystem (Hadoop 2.x)</description>
      </property>
      <property>
        <name>fs.defaultFS</name>
        <value>alluxio://sandbox01.p02.eng.sjc01.qualys.com:19998</value>
      </property>
      <property>
        <name>spark.master</name>
        <value>spark://spark-hadoop-master:6066</value>
      </property>
      <property>
        <name>spark.eventLog.dir</name>
        <value>alluxio://sandbox01.p02.eng.sjc01.qualys.com:19998/sparkeventLog</value>
      </property>
      <property>
        <name>spark.home</name>
        <value>/opt/spark</value>
      </property>
      <property>
        <name>datanucleus.autoCreateSchema</name>
        <value>false</value>
      </property>
      <property>
        <name>hive.metastore.schema.verification</name>
        <value>false</value>
      </property>
      <property>
        <name>datanucleus.schema.autoCreateAll</name>
        <value>false</value>
      </property>
      <property>
        <name>datanucleus.fixedDatastore</name>
        <value>true</value>
      </property>
    </configuration>