apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "datalake.spark-master.fullname" . }}
  labels:
    app: {{ template "datalake.spark-master.name" . }}
    chart: {{ template "datalake.subchart" . }}
    release: {{ .Release.Name }}
data:
  spark-defaults.conf: |
    spark.master spark://spark-master:7077
    spark.app.id QualysSpark
    spark.hadoop.datanucleus.autoCreateSchema false
    spark.executor.memoryOverhead   384m
    spark.driver.memory 4g
    spark.driver.memoryOverhead  384m
    spark.scheduler.minRegisteredResourcesRatio 0.8
    spark.sql.hive.metastore.version 3.1.0
    spark.sql.hive.metastore.schema.verification false
    spark.sql.hive.convertMetastoreOrc true
    spark.sql.orc.impl native

  hive-site.xml: |
    <configuration>
      <property>
        <name>hive.metastore.schema.verification</name>
        <value>false</value>
      </property>
      <property>
        <name>javax.jdo.option.ConnectionURL</name>
        <value>jdbc:postgresql://postgresql:5432/metastore</value>
      </property>
      <property>
        <name>javax.jdo.option.ConnectionDriverName</name>
        <value>org.postgresql.Driver</value>
      </property>
      <property>
        <name>javax.jdo.option.ConnectionUserName</name>
        <value>hive</value>
      </property>
      <property>
        <name>javax.jdo.option.ConnectionPassword</name>
        <value>hive</value>
      </property>
      <property>
        <name>datanucleus.autoCreateSchema</name>
        <value>false</value>
      </property>
      <property>
        <name>hive.execution.engine</name>
        <value>spark</value>
      </property>
      <property>
        <name>fs.alluxio.impl</name>
        <value>alluxio.hadoop.FileSystem</value>
      </property>
      <property>
        <name>fs.AbstractFileSystem.alluxio.impl</name>
        <value>alluxio.hadoop.AlluxioFileSystem</value>
      </property>
      <property>
        <name>fs.defaultFS</name>
        <value>alluxio://alluxio-master:19998</value>
      </property>
      <property>
        <name>spark.master</name>
        <value>spark://spark-master:6066</value>
      </property>
      <property>
        <name>spark.eventLog.dir</name>
        <value>alluxio://alluxio-master:19998/sparkeventLog</value>
      </property>
      <property>
        <name>spark.home</name>
        <value>/opt/spark</value>
      </property>
      <property>
        <name>spark.sql.hive.convertMetastoreOrc</name>
        <value>true</value>
      </property>
      <property>
        <name>spark.sql.orc.impl</name>
        <value>native</value>
      </property>
      <property>
        <name>spark.executor.memory</name>
        <value>3g</value>
      </property>
      <property>
        <name>spark.cores.max</name>
        <value>3</value>
      </property>
    </configuration>