apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "datalake.spark-proxy.fullname" . }}
  labels:
    app: {{ template "datalake.spark-proxy.name" . }}
    chart: {{ template "datalake.subchart" . }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "datalake.spark-proxy.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "datalake.spark-proxy.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-proxy
          image: "{{ .Values.image.proxy.repository }}:{{ .Values.image.proxy.tag }}"
          imagePullPolicy: {{ .Values.image.proxy.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
              initialDelaySeconds: 120
              timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: http
              initialDelaySeconds: 90
              timeoutSeconds: 5
          args:
            - spark-master:8080
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
