apiVersion: v1
kind: Service
metadata:
  name: {{ template "datalake.spark-master.hostname" . }}
  labels:
    app: {{ template "datalake.spark-master.name" . }}
    chart: {{ template "datalake.subchart" . }}
    release: {{ .Release.Name }}
spec:
  clusterIP: {{ .Values.service.spark.type }}
  ports:
    - port: {{ .Values.service.spark.portUI }}
      targetPort: webui
      protocol: TCP
      name: webui
    - port: {{ .Values.service.spark.portRPC }}
      targetPort: rpc 
      name: rpc
  selector:
    app: {{ template "datalake.spark-master.name" . }}
    release: {{ .Release.Name }}
