apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "spark-master.fullname" . }}
  labels:
    app: {{ template "spark-master.name" . }}
    chart: {{ template "spark-master.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "spark-master.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "spark-master.name" . }}
        release: {{ .Release.Name }}
    spec:
      hostname: {{ template "spark-master.name" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: {{ .Values.image.command }}
          ports:
            - name: rpc
              containerPort: 7077
              protocol: TCP
            - name: webui
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: webui
          readinessProbe:
            httpGet:
              path: /
              port: webui
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}