apiVersion: v1
appVersion: 0.23.2
description: Provides easy monitoring definitions for Kubernetes services, and deployment
  and management of Prometheus instances.
engine: gotpl
home: https://github.com/coreos/prometheus-operator
keywords:
- operator
- prometheus
name: prometheus-operator
sources:
- https://github.com/coreos/prometheus-operator
version: 0.1.0
