apiVersion: v1
kind: Service
metadata:
  name: {{ template "datalake.jenkins.fullname" . }}
  labels:
    app: {{ template "datalake.jenkins.name" . }}
    chart: {{ template "datalake.subchart" . }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ui }}
      targetPort: ui
      protocol: TCP
      name: ui
  selector:
    app: {{ template "datalake.jenkins.name" . }}
    release: {{ .Release.Name }}
